version: '3.8'

services:
  php:
    image: php:fpm
    volumes:
      - ./public:/var/www/html

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/etc/nginx/conf.d
      - ./public:/var/www/html
    depends_on:
      - php
